In [2]:
import pandas as pd

Q1 create dataset

In [3]:
data= {
    'Tid':[1,2,3,4,5,6,7,8,9,10],
    'Refund':['Yes','No','No','Yes','No','No','Yes','No','No','No'],
    'MaritalStatus':['Single','Married','Single','Married','Divorced','Married','Divorced','Single','Married','Single'],
    'Cheat': ['No','No','No','No','Yes','No','No','Yes','No','Yes']
}

Q2  From the above table that you have created, locate row 0, 4, 7 and 8 using DataFrame.

In [4]:
df = pd.DataFrame(data)
df.iloc[[0,4,7,8]]

   Tid Refund MaritalStatus Cheat
0    1    Yes        Single    No
4    5     No      Divorced   Yes
7    8     No        Single   Yes
8    9     No       Married    No

Q3.Navigate the DataFrame and do the following task for the table created in question 1:

 1.Select row from index 3 to 7.

2. Select row from index 4 to 8, and column 2 to 4.

3. Select all rows with column index 1 to 3 (include index 3 during selection).

In [5]:
print(df.iloc[3:8])

   Tid Refund MaritalStatus Cheat
3    4    Yes       Married    No
4    5     No      Divorced   Yes
5    6     No       Married    No
6    7    Yes      Divorced    No
7    8     No        Single   Yes

In [6]:
print(df.iloc[4:9,2:5])

  MaritalStatus Cheat
4      Divorced   Yes
5       Married    No
6      Divorced    No
7        Single   Yes
8       Married    No

In [7]:
print(df.iloc[:,1:4])

  Refund MaritalStatus Cheat
0    Yes        Single    No
1     No       Married    No
2     No        Single    No
3    Yes       Married    No
4     No      Divorced   Yes
5     No       Married    No
6    Yes      Divorced    No
7     No        Single   Yes
8     No       Married    No
9     No        Single   Yes

Q4. Read a csv file and display its first five rows.  Note-: Download dataset from https://www.kaggle.com/datasets/uciml/iris)

In [13]:
df=pd.read_csv('Iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [14]:
print(df)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]

Q5 From the csv file (uploaded in the Q.4) delete row 4, and delete column 3. Display the result.

In [15]:
# Delete row with index 4
df = df.drop(index=4)

# Delete column with index 3
df = df.drop(df.columns[3], axis=1)

print(df)

      Id  SepalLengthCm  SepalWidthCm  PetalWidthCm         Species
0      1            5.1           3.5           0.2     Iris-setosa
1      2            4.9           3.0           0.2     Iris-setosa
2      3            4.7           3.2           0.2     Iris-setosa
3      4            4.6           3.1           0.2     Iris-setosa
5      6            5.4           3.9           0.4     Iris-setosa
..   ...            ...           ...           ...             ...
145  146            6.7           3.0           2.3  Iris-virginica
146  147            6.3           2.5           1.9  Iris-virginica
147  148            6.5           3.0           2.0  Iris-virginica
148  149            6.2           3.4           2.3  Iris-virginica
149  150            5.9           3.0           1.8  Iris-virginica

[149 rows x 5 columns]

Q.6 Create a sample dataset (employees.csv) containing information about employees in a company. WAP to determine the following using dataset

In [16]:
# a) Shape (number of rows and columns) of the DataFrame
df = pd.read_csv("employee.csv")
print(df.shape)

(5, 10)

In [17]:
# b) Summary of the DataFrame that includes the data types and non-null counts for each column.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes

In [18]:
# c) Generate descriptive statistics.
print(df.describe())

       Employee_ID        Age       Salary  Years_of_Experience   Bonus  \
count     5.000000   5.000000      5.00000             5.000000     5.0
mean    103.000000  34.000000  60000.00000             7.400000  5500.0
std       1.581139   5.612486   7905.69415             3.847077  1000.0
min     101.000000  28.000000  50000.00000             3.000000  4500.0
25%     102.000000  29.000000  55000.00000             4.000000  5000.0
50%     103.000000  34.000000  60000.00000             8.000000  5000.0
75%     104.000000  38.000000  65000.00000            10.000000  6000.0
max     105.000000  41.000000  70000.00000            12.000000  7000.0

         Rating
count  5.000000
mean   4.100000
std    0.494975
min    3.500000
25%    3.800000
50%    4.000000
75%    4.500000
max    4.700000

In [19]:
# d) Display the first 5 rows and last 3 rows of the dataset.
print(df.head(5))
print(df.tail(3))

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

In [21]:
# e) Calculate the following statistics from the dataset:
# i. Average salary
print("Average Salary:",df["Salary"].mean())
# ii. Total bonus
print("Total bonus",df["Bonus"].sum())
# iii. Youngest employee's age
print("Youngest Employee Age:",df["Age"].min())
# iv. Highest performance rating
print("Highest Performance Rating:",df["Rating"].max())

Average Salary: 60000.0
Total bonus 27500
Youngest Employee Age: 28
Highest Performance Rating: 4.7

In [ ]:
# f) Sort by Salary in descending order
sorted_df = df.sort_values(by="Salary", ascending=False)
print("Salary in Descending Order:",sorted_df)

In [23]:
# g) Add Category column based on Rating
def categorize_rating(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"
df["Category"] = df["Rating"].apply(categorize_rating)
print(df[["Name", "Rating", "Category"]])

      Name  Rating   Category
0    Alice     4.5  Excellent
1      Bob     4.0       Good
2  Charlie     3.8    Average
3    Diana     4.7  Excellent
4   Edward     3.5    Average

In [25]:
# h) Identify missing values
print(df.isnull().sum())

Employee_ID            0
Name                   0
Department             0
Age                    0
Salary                 0
Years_of_Experience    0
Joining_Date           0
Gender                 0
Bonus                  0
Rating                 0
Category               0
dtype: int64

In [26]:
# i) Rename Employee_ID to ID
df.rename(columns={"Employee_ID": "ID"}, inplace=True)
print(df)

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
0  101    Alice         HR   29   50000                    4   2020-03-15
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
3  104    Diana  Marketing   28   55000                    3   2021-02-10
4  105   Edward      Sales   38   60000                   12   2010-11-25

   Gender  Bonus  Rating   Category
0  Female   5000     4.5  Excellent
1    Male   7000     4.0       Good
2    Male   6000     3.8    Average
3  Female   4500     4.7  Excellent
4    Male   5000     3.5    Average

In [28]:
# j) Find employees

# i. More than 5 years of experience
print("empoyees with experience >5 years")
print(df[df["Years_of_Experience"] > 5])

# ii. Belong to IT department
print("empoyees that Belong to IT department")
print(df[df["Department"] == "IT"])

empoyees with experience >5 years
    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
4  105   Edward      Sales   38   60000                   12   2010-11-25

  Gender  Bonus  Rating Category
1   Male   7000     4.0     Good
2   Male   6000     3.8  Average
4   Male   5000     3.5  Average
empoyees that Belong to IT department
    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01

  Gender  Bonus  Rating Category
1   Male   7000     4.0     Good
2   Male   6000     3.8  Average

In [30]:
# k) Add Tax column (10% of Salary)
df["Tax"] = df["Salary"] * 0.10
print("Tax column added:")
print(df)

Tax column added:
    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
0  101    Alice         HR   29   50000                    4   2020-03-15
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
3  104    Diana  Marketing   28   55000                    3   2021-02-10
4  105   Edward      Sales   38   60000                   12   2010-11-25

   Gender  Bonus  Rating   Category     Tax
0  Female   5000     4.5  Excellent  5000.0
1    Male   7000     4.0       Good  7000.0
2    Male   6000     3.8    Average  6500.0
3  Female   4500     4.7  Excellent  5500.0
4    Male   5000     3.5    Average  6000.0

In [32]:
# l) Save modified DataFrame to new CSV
df.to_csv("employees_modified.csv", index=False)
print(" Modified dataset saved as employees_modified.csv")

 Modified dataset saved as employees_modified.csv